import { BookOpen, CalendarDays, ChevronLeft, ChevronRight, Pencil, Plus, Trash2 } from 'lucide-react'
import { useMemo, useState, type FormEvent } from 'react'
import type { Course, CourseDay, CoursePeriod } from '../../domain/models'
import { formatLocalDate } from '../../domain/localDate'
import { useLibraryStore } from '../../state/useLibraryStore'
import { calendarDates, dayNumber, isTodoCompletedOn, recurringTodoOccursOn } from './plannerDates'
import { scheduleDays, schedulePeriods, scheduleShortDays } from './scheduleConstants'

type CourseDraft = Omit<Course, 'id'>
const emptyCourse = (): CourseDraft => ({ title: '', day: 1, period: 1, teacher: '', location: '', weeks: '全周', note: '' })

export function CalendarScheduleView() {
  const { data, addCourse, updateCourse, deleteCourse, openDiary } = useLibraryStore()
  const [mode, setMode] = useState<'calendar' | 'schedule'>('calendar')
  const [date, setDate] = useState(formatLocalDate())
  const [month, setMonth] = useState(() => { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), 1, 12) })
  const [editingId, setEditingId] = useState<string>()
  const [course, setCourse] = useState<CourseDraft>(emptyCourse)
  const selectedDay = dayNumber(date)
  const dayCourses = useMemo(() => data.planner.courses.filter((item) => item.day === selectedDay).sort((a, b) => a.period - b.period), [data.planner.courses, selectedDay])
  const selectedTodos = data.planner.todos.filter((todo) => recurringTodoOccursOn(todo, date))
  const storedEntry = data.planner.diaryEntries.find((entry) => entry.date === date)
  const monthDates = calendarDates(month)

  const chooseDate = (value: string) => { setDate(value); const picked = new Date(`${value}T12:00:00`); setMonth(new Date(picked.getFullYear(), picked.getMonth(), 1, 12)) }
  const submitCourse = (event: FormEvent) => { event.preventDefault(); if (!course.title.trim()) return; const value = { ...course, title: course.title.trim() }; if (editingId) updateCourse(editingId, value); else addCourse(value); setEditingId(undefined); setCourse(emptyCourse()) }
  const editCourse = (item: Course) => { setEditingId(item.id); setCourse({ title: item.title, day: item.day, period: item.period, teacher: item.teacher, location: item.location, weeks: item.weeks, note: item.note }) }

  return <main className="planner-view scroll-view"><header className="page-header planner-header"><div><p className="eyebrow">日常与节奏</p><h1>日历与课表</h1><p>在月历里看见课程和事项，需要记录时再前往创作空间的日记。</p></div><div className="planner-tabs"><button className={mode === 'calendar' ? 'active' : ''} onClick={() => setMode('calendar')}><CalendarDays size={15} />日历</button><button className={mode === 'schedule' ? 'active' : ''} onClick={() => setMode('schedule')}><CalendarDays size={15} />课表</button></div></header>
    {mode === 'calendar' && <div className="calendar-layout"><section className="month-card"><header><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1, 12))}><ChevronLeft size={17} /></button><h2>{month.getFullYear()} 年 {month.getMonth() + 1} 月</h2><button onClick={() => { const now = new Date(); setMonth(new Date(now.getFullYear(), now.getMonth(), 1, 12)); setDate(formatLocalDate(now)) }}>今天</button><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1, 12))}><ChevronRight size={17} /></button></header><div className="month-grid">{scheduleShortDays.map((day) => <strong className="month-weekday" key={day}>周{day}</strong>)}{monthDates.map((item) => { const key = formatLocalDate(item); const weekday = dayNumber(key); const courses = data.planner.courses.filter((entry) => entry.day === weekday); const todos = data.planner.todos.filter((todo) => recurringTodoOccursOn(todo, key) && !isTodoCompletedOn(todo, key)); const diary = data.planner.diaryEntries.some((entry) => entry.date === key); return <button className={`${item.getMonth() === month.getMonth() ? '' : 'outside '} ${key === date ? 'selected' : ''}`} key={key} onClick={() => chooseDate(key)}><span>{item.getDate()}</span><div>{courses.length > 0 && <i>{courses.length} 节课</i>}{todos.length > 0 && <i>{todos.length} 待办</i>}{diary && <i>有日记</i>}</div></button> })}</div></section><aside className="calendar-agenda"><header><span>{date}</span><h2>{scheduleDays[selectedDay - 1]}</h2></header><h3>课程</h3>{dayCourses.map((item) => <article key={item.id}><span>{schedulePeriods[item.period - 1].time}</span><strong>{item.title}</strong><small>{[item.teacher, item.location].filter(Boolean).join(' · ')}</small></article>)}{dayCourses.length === 0 && <p>没有固定课程</p>}<h3>待办</h3>{selectedTodos.map((todo) => <article key={todo.id} className={isTodoCompletedOn(todo, date) ? 'done' : ''}><strong>{todo.title}</strong><small>{todo.repeat === 'daily' ? '每天' : todo.repeat === 'weekdays' ? '工作日' : todo.repeat === 'weekly' ? '每周' : '当天事项'}</small></article>)}{selectedTodos.length === 0 && <p>没有当天待办</p>}<button className="ghost-button agenda-journal" onClick={() => openDiary(date)}><BookOpen size={14} />{storedEntry ? '打开这天的日记' : '写这天的日记'}</button></aside></div>}
    {mode === 'schedule' && <div className="schedule-layout"><section className="schedule-board"><div className="schedule-grid"><div className="schedule-corner" />{scheduleDays.map((day) => <div className="schedule-day" key={day}>{day}</div>)}{schedulePeriods.flatMap((period) => [<div className="schedule-period" key={`p-${period.id}`}><strong>{period.label}</strong><span>{period.time}</span></div>, ...scheduleDays.map((_, index) => <div className="schedule-cell" key={`${period.id}-${index + 1}`}>{data.planner.courses.filter((item) => item.period === period.id && item.day === index + 1).map((item) => <button key={item.id} onClick={() => editCourse(item)}><strong>{item.title}</strong><span>{[item.teacher, item.note, item.weeks, item.location].filter(Boolean).join('；')}</span></button>)}</div>)])}</div></section><form className="course-editor" onSubmit={submitCourse}><h2>{editingId ? '编辑课程' : '添加课程'}</h2><label>课程名称<input value={course.title} onChange={(event) => setCourse({ ...course, title: event.target.value })} /></label><div><label>星期<select value={course.day} onChange={(event) => setCourse({ ...course, day: Number(event.target.value) as CourseDay })}>{scheduleDays.map((day, index) => <option value={index + 1} key={day}>{day}</option>)}</select></label><label>节次<select value={course.period} onChange={(event) => setCourse({ ...course, period: Number(event.target.value) as CoursePeriod })}>{schedulePeriods.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label></div><label>教师<input value={course.teacher} onChange={(event) => setCourse({ ...course, teacher: event.target.value })} /></label><label>地点<input value={course.location} onChange={(event) => setCourse({ ...course, location: event.target.value })} /></label><label>周次<input value={course.weeks} onChange={(event) => setCourse({ ...course, weeks: event.target.value })} /></label><label>性质/备注<textarea value={course.note} onChange={(event) => setCourse({ ...course, note: event.target.value })} rows={2} /></label><div className="course-actions"><button className="primary-button" type="submit">{editingId ? <Pencil size={14} /> : <Plus size={14} />}{editingId ? '保存修改' : '加入课表'}</button>{editingId && <><button className="ghost-button" type="button" onClick={() => { setEditingId(undefined); setCourse(emptyCourse()) }}>取消</button><button className="danger-button" type="button" onClick={() => { deleteCourse(editingId); setEditingId(undefined); setCourse(emptyCourse()) }}><Trash2 size={14} />删除</button></>}</div></form></div>}
  </main>
}
