import { BookOpen, CalendarDays, ChevronLeft, ChevronRight, Pencil, Plus, Save, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState, type FormEvent } from 'react'
import type { Course, CourseDay, CoursePeriod } from '../../domain/models'
import { formatLocalDate } from '../../domain/localDate'
import { useLibraryStore } from '../../state/useLibraryStore'
import { calendarDates, dayNumber, isTodoCompletedOn, recurringTodoOccursOn } from './plannerDates'

const days = ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日']
const shortDays = ['一', '二', '三', '四', '五', '六', '日']
const periods = [{ id: 1, label: '第1节', time: '8:00～9:35' }, { id: 2, label: '第2节', time: '9:50～12:15' }, { id: 3, label: '第3节', time: '13:30～15:05' }, { id: 4, label: '第4节', time: '15:20～16:55' }, { id: 5, label: '第5节', time: '17:05～18:40' }, { id: 6, label: '第6节', time: '19:20～21:45' }] as const
type CourseDraft = Omit<Course, 'id'>
const emptyCourse = (): CourseDraft => ({ title: '', day: 1, period: 1, teacher: '', location: '', weeks: '全周', note: '' })

export function JournalScheduleView() {
  const { data, saveDiaryEntry, addCourse, updateCourse, deleteCourse } = useLibraryStore()
  const [mode, setMode] = useState<'calendar' | 'schedule' | 'journal'>('calendar')
  const [date, setDate] = useState(formatLocalDate())
  const [month, setMonth] = useState(() => { const now = new Date(); return new Date(now.getFullYear(), now.getMonth(), 1, 12) })
  const storedEntry = data.planner.diaryEntries.find((entry) => entry.date === date)
  const [title, setTitle] = useState(storedEntry?.title ?? '')
  const [content, setContent] = useState(storedEntry?.content ?? '')
  const [saved, setSaved] = useState(false)
  const [editingId, setEditingId] = useState<string>()
  const [course, setCourse] = useState<CourseDraft>(emptyCourse)
  const selectedDay = dayNumber(date)
  const dayCourses = useMemo(() => data.planner.courses.filter((item) => item.day === selectedDay).sort((a, b) => a.period - b.period), [data.planner.courses, selectedDay])
  const selectedTodos = data.planner.todos.filter((todo) => recurringTodoOccursOn(todo, date))
  const monthDates = calendarDates(month)

  useEffect(() => { setTitle(storedEntry?.title ?? ''); setContent(storedEntry?.content ?? ''); setSaved(false) }, [date, storedEntry?.title, storedEntry?.content])
  const chooseDate = (value: string) => { setDate(value); const picked = new Date(`${value}T12:00:00`); setMonth(new Date(picked.getFullYear(), picked.getMonth(), 1, 12)) }
  const saveJournal = () => { saveDiaryEntry({ date, title: title.trim(), content, updatedAt: new Date().toISOString() }); setSaved(true) }
  const submitCourse = (event: FormEvent) => { event.preventDefault(); if (!course.title.trim()) return; const value = { ...course, title: course.title.trim() }; if (editingId) updateCourse(editingId, value); else addCourse(value); setEditingId(undefined); setCourse(emptyCourse()) }
  const editCourse = (item: Course) => { setEditingId(item.id); setCourse({ title: item.title, day: item.day, period: item.period, teacher: item.teacher, location: item.location, weeks: item.weeks, note: item.note }) }

  return <main className="planner-view scroll-view"><header className="page-header planner-header"><div><p className="eyebrow">日常与节奏</p><h1>日历与课表</h1><p>在月历里看见课程和事项，也为某一天留下日记。</p></div><div className="planner-tabs">{([['calendar', CalendarDays, '日历'], ['schedule', CalendarDays, '课表'], ['journal', BookOpen, '日记']] as const).map(([id, Icon, label]) => <button className={mode === id ? 'active' : ''} onClick={() => setMode(id)} key={id}><Icon size={15} />{label}</button>)}</div></header>
    {mode === 'calendar' && <div className="calendar-layout"><section className="month-card"><header><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1, 12))}><ChevronLeft size={17} /></button><h2>{month.getFullYear()} 年 {month.getMonth() + 1} 月</h2><button onClick={() => { const now = new Date(); setMonth(new Date(now.getFullYear(), now.getMonth(), 1, 12)); setDate(formatLocalDate(now)) }}>今天</button><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1, 12))}><ChevronRight size={17} /></button></header><div className="month-grid">{shortDays.map((day) => <strong className="month-weekday" key={day}>周{day}</strong>)}{monthDates.map((item) => { const key = formatLocalDate(item); const weekday = dayNumber(key); const courses = data.planner.courses.filter((entry) => entry.day === weekday); const todos = data.planner.todos.filter((todo) => recurringTodoOccursOn(todo, key) && !isTodoCompletedOn(todo, key)); const diary = data.planner.diaryEntries.some((entry) => entry.date === key); return <button className={`${item.getMonth() === month.getMonth() ? '' : 'outside '} ${key === date ? 'selected' : ''}`} key={key} onClick={() => chooseDate(key)}><span>{item.getDate()}</span><div>{courses.length > 0 && <i>{courses.length} 节课</i>}{todos.length > 0 && <i>{todos.length} 待办</i>}{diary && <i>有日记</i>}</div></button> })}</div></section><aside className="calendar-agenda"><header><span>{date}</span><h2>{days[selectedDay - 1]}</h2></header><h3>课程</h3>{dayCourses.map((item) => <article key={item.id}><span>{periods[item.period - 1].time}</span><strong>{item.title}</strong><small>{[item.teacher, item.location].filter(Boolean).join(' · ')}</small></article>)}{dayCourses.length === 0 && <p>没有固定课程</p>}<h3>待办</h3>{selectedTodos.map((todo) => <article key={todo.id} className={isTodoCompletedOn(todo, date) ? 'done' : ''}><strong>{todo.title}</strong><small>{todo.repeat === 'daily' ? '每天' : todo.repeat === 'weekdays' ? '工作日' : todo.repeat === 'weekly' ? '每周' : '当天事项'}</small></article>)}{selectedTodos.length === 0 && <p>没有当天待办</p>}<button className="ghost-button agenda-journal" onClick={() => setMode('journal')}><BookOpen size={14} />{storedEntry ? '打开这天的日记' : '写这天的日记'}</button></aside></div>}
    {mode === 'journal' && <div className="journal-layout"><section className="journal-editor"><div className="journal-date-row"><label>日期<input type="date" value={date} onChange={(event) => event.target.value && chooseDate(event.target.value)} /></label><span>{days[selectedDay - 1]}</span></div><input className="journal-title" value={title} onChange={(event) => { setTitle(event.target.value); setSaved(false) }} placeholder="给今天一个标题" /><textarea value={content} onChange={(event) => { setContent(event.target.value); setSaved(false) }} placeholder="今天发生了什么？此刻有什么想记住的？" /><footer><small>{storedEntry ? `上次保存于 ${new Date(storedEntry.updatedAt).toLocaleString()}` : '这一天还没有日记'}</small><button className="primary-button" onClick={saveJournal}><Save size={14} />{saved ? '已保存' : '保存日记'}</button></footer></section><aside className="today-courses"><h2>{days[selectedDay - 1]}的课程</h2>{dayCourses.map((item) => <article key={item.id}><span>{periods[item.period - 1].time}</span><strong>{item.title}</strong><small>{[item.teacher, item.location].filter(Boolean).join(' · ') || item.weeks}</small></article>)}{dayCourses.length === 0 && <p>今天没有安排固定课程。</p>}</aside></div>}
    {mode === 'schedule' && <div className="schedule-layout"><section className="schedule-board"><div className="schedule-grid"><div className="schedule-corner" />{days.map((day) => <div className="schedule-day" key={day}>{day}</div>)}{periods.flatMap((period) => [<div className="schedule-period" key={`p-${period.id}`}><strong>{period.label}</strong><span>{period.time}</span></div>, ...days.map((_, index) => <div className="schedule-cell" key={`${period.id}-${index + 1}`}>{data.planner.courses.filter((item) => item.period === period.id && item.day === index + 1).map((item) => <button key={item.id} onClick={() => editCourse(item)}><strong>{item.title}</strong><span>{[item.teacher, item.note, item.weeks, item.location].filter(Boolean).join('；')}</span></button>)}</div>)])}</div></section><form className="course-editor" onSubmit={submitCourse}><h2>{editingId ? '编辑课程' : '添加课程'}</h2><label>课程名称<input value={course.title} onChange={(event) => setCourse({ ...course, title: event.target.value })} placeholder="例如：专业课程实践" /></label><div><label>星期<select value={course.day} onChange={(event) => setCourse({ ...course, day: Number(event.target.value) as CourseDay })}>{days.map((day, index) => <option value={index + 1} key={day}>{day}</option>)}</select></label><label>节次<select value={course.period} onChange={(event) => setCourse({ ...course, period: Number(event.target.value) as CoursePeriod })}>{periods.map((item) => <option value={item.id} key={item.id}>{item.label}</option>)}</select></label></div><label>教师<input value={course.teacher} onChange={(event) => setCourse({ ...course, teacher: event.target.value })} /></label><label>地点<input value={course.location} onChange={(event) => setCourse({ ...course, location: event.target.value })} /></label><label>周次<input value={course.weeks} onChange={(event) => setCourse({ ...course, weeks: event.target.value })} /></label><label>性质/备注<textarea value={course.note} onChange={(event) => setCourse({ ...course, note: event.target.value })} rows={2} /></label><div className="course-actions"><button className="primary-button" type="submit">{editingId ? <Pencil size={14} /> : <Plus size={14} />}{editingId ? '保存修改' : '加入课表'}</button>{editingId && <><button className="ghost-button" type="button" onClick={() => { setEditingId(undefined); setCourse(emptyCourse()) }}>取消</button><button className="danger-button" type="button" onClick={() => { deleteCourse(editingId); setEditingId(undefined); setCourse(emptyCourse()) }}><Trash2 size={14} />删除</button></>}</div></form></div>}
  </main>
}
