import { fireEvent, render, screen, waitFor, within } from '@testing-library/react'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { createSeedLibrary } from '../../domain/seed'
import { useLibraryStore } from '../../state/useLibraryStore'
import { ExperiencesView } from './ExperiencesView'

vi.mock('../../infrastructure/libraryRepository', () => ({ libraryRepository: { save: vi.fn().mockResolvedValue(undefined) } }))
vi.mock('../../infrastructure/experienceCovers', async importOriginal => {
  const actual = await importOriginal<typeof import('../../infrastructure/experienceCovers')>()
  return { ...actual, experienceCovers: { ...actual.experienceCovers, hasKey: vi.fn().mockResolvedValue(false), search: vi.fn().mockRejectedValue(new Error('未配置微信读书密钥')) } }
})
describe('experience paper cards and personal tier board', () => {
  beforeEach(() => { useLibraryStore.setState({ data: createSeedLibrary() }) })
  it('filters work categories directly and preserves the selection, personal notes and ranks after editing', () => {
    const store = useLibraryStore.getState()
    store.saveExperience({ title: '第一部', category: 'novel', creator: '作者', dateText: '去年', note: '保留这段感想', tier: 'top', paperStyle: 'linen' })
    store.saveExperience({ title: '第二部', category: 'anime', creator: '', dateText: '', note: '', paperStyle: 'blue' })
    render(<ExperiencesView />)
    expect(screen.queryByText('筛选与设置')).not.toBeInTheDocument()
    expect(screen.queryByText('封面来源设置 · 可选')).not.toBeInTheDocument()
    fireEvent.change(screen.getByLabelText('筛选作品类别'), { target: { value: 'novel' } })
    expect(screen.queryByRole('button', { name: '查看第二部' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '查看第一部' }))
    fireEvent.click(screen.getByRole('button', { name: '保存这一页' }))
    expect(screen.getByLabelText('筛选作品类别')).toHaveValue('novel')
    fireEvent.change(screen.getByLabelText('筛选作品类别'), { target: { value: '' } })
    expect(screen.getByRole('button', { name: '查看第二部' })).toBeInTheDocument()
    expect(screen.queryByLabelText('经历卡片编辑')).not.toBeInTheDocument()
    expect(useLibraryStore.getState().data.experiences?.entries.find(entry => entry.title === '第一部')).toMatchObject({ note: '保留这段感想', tier: 'top', dateText: '去年' })
  })
  it('combines type and text filters in the cover wall and tier board without changing saved entries', () => {
    const store = useLibraryStore.getState()
    store.saveExperience({ title: '动漫甲', category: 'anime', creator: '', dateText: '', note: '', paperStyle: 'blue', tier: 'top' })
    store.saveExperience({ title: '动漫乙', category: 'anime', creator: '', dateText: '', note: '', paperStyle: 'linen' })
    store.saveExperience({ title: '小说甲', category: 'novel', creator: '', dateText: '', note: '', paperStyle: 'linen' })
    const original = structuredClone(useLibraryStore.getState().data.experiences)
    render(<ExperiencesView />)
    fireEvent.change(screen.getByLabelText('筛选作品类别'), { target: { value: 'anime' } })
    fireEvent.change(screen.getByLabelText('搜索经历'), { target: { value: '甲' } })
    expect(screen.getByRole('button', { name: '查看动漫甲' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '查看动漫乙' })).not.toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '查看小说甲' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '从夯到拉' }))
    expect(within(screen.getByLabelText('从夯到拉个人排行')).getByRole('button', { name: '查看动漫甲' })).toBeInTheDocument()
    expect(screen.queryByRole('button', { name: '查看小说甲' })).not.toBeInTheDocument()
    expect(useLibraryStore.getState().data.experiences).toEqual(original)
    fireEvent.change(screen.getByLabelText('筛选作品类别'), { target: { value: 'film' } })
    expect(screen.getByText('这一页，还没有找到匹配的回忆')).toBeInTheDocument()
  })
  it('does not apply work categories to places and resets the type when switching groups', () => {
    const store = useLibraryStore.getState()
    store.saveExperience({ title: '作品甲', category: 'anime', creator: '', dateText: '', note: '', paperStyle: 'blue' })
    store.saveExperience({ title: '海边', category: 'place', creator: '', dateText: '', note: '', paperStyle: 'blue' })
    render(<ExperiencesView />)
    fireEvent.change(screen.getByLabelText('筛选作品类别'), { target: { value: 'film' } })
    fireEvent.click(screen.getByRole('button', { name: '足迹' }))
    expect(screen.queryByLabelText('筛选作品类别')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: '查看海边' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '作品' }))
    expect(screen.getByLabelText('筛选作品类别')).toHaveValue('')
    expect(screen.getByRole('button', { name: '查看作品甲' })).toBeInTheDocument()
  })
  it('records a novel with only title and optional impression, without requiring images or date', async () => {
    render(<ExperiencesView />)
    fireEvent.click(screen.getByRole('button', { name: '收进一部作品' }))
    const editor = within(screen.getByLabelText('经历卡片编辑'))
    fireEvent.change(editor.getByLabelText('名称'), { target: { value: '诡秘之主' } })
    fireEvent.change(editor.getByLabelText('留下的感想 · 可选'), { target: { value: '读完后，仍然记得那些人。' } })
    fireEvent.click(editor.getByRole('button', { name: '保存这一页' }))
    expect(await screen.findByRole('button', { name: '查看诡秘之主' })).toBeInTheDocument()
    expect(useLibraryStore.getState().data.experiences?.entries[0]).toMatchObject({ title: '诡秘之主', note: '读完后，仍然记得那些人。', dateText: '' })
    expect(useLibraryStore.getState().data.experiences?.entries[0].tier).toBeUndefined()
  })
  it('ranks using the editor, separates visited places and keeps soft deletion recoverable', async () => {
    const store = useLibraryStore.getState()
    const id = store.saveExperience({ title: '作品甲', category: 'anime', creator: '', dateText: '', note: '', paperStyle: 'blue' })
    store.saveExperience({ title: '杭州', category: 'place', creator: '', dateText: '去年秋天', note: '湖边散步', paperStyle: 'linen' })
    render(<ExperiencesView />)
    fireEvent.click(screen.getByRole('button', { name: '从夯到拉' }))
    fireEvent.click(screen.getByRole('button', { name: '查看作品甲' }))
    fireEvent.change(screen.getByLabelText('个人档位'), { target: { value: 'top' } })
    fireEvent.click(screen.getByRole('button', { name: '保存这一页' }))
    expect(await screen.findByRole('button', { name: '查看作品甲' })).toBeInTheDocument()
    expect(useLibraryStore.getState().data.experiences?.entries.find(item => item.id === id)?.tier).toBe('top')
    expect(screen.queryByRole('button', { name: '查看杭州' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '查看作品甲' }))
    fireEvent.click(screen.getByRole('button', { name: '删除这张卡片' }))
    fireEvent.click(screen.getByRole('button', { name: '删除并移入收纳袋' }))
    expect(screen.queryByRole('button', { name: '查看作品甲' })).not.toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '收纳袋 · 1' }))
    fireEvent.click(screen.getByRole('button', { name: '放回经历册' }))
    expect(await screen.findByRole('button', { name: '查看作品甲' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '足迹' }))
    expect(screen.getByRole('button', { name: '查看杭州' })).toBeInTheDocument()
  })
  it('confirms both deletion steps and does not resurrect discarded edits after restoration', () => {
    const store = useLibraryStore.getState()
    const id = store.saveExperience({ title: '误录入的作品', category: 'novel', creator: '', dateText: '', note: '原感想', paperStyle: 'linen' })
    render(<ExperiencesView />)
    fireEvent.click(screen.getByRole('button', { name: '查看误录入的作品' }))
    fireEvent.change(screen.getByLabelText('名称'), { target: { value: '未保存的名字' } })
    fireEvent.click(screen.getByRole('button', { name: '删除这张卡片' }))
    fireEvent.click(screen.getByRole('button', { name: '先保留' }))
    expect(useLibraryStore.getState().data.experiences?.entries[0].deletedAt).toBeUndefined()
    fireEvent.click(screen.getByRole('button', { name: '删除这张卡片' }))
    fireEvent.click(screen.getByRole('button', { name: '删除并移入收纳袋' }))
    fireEvent.click(screen.getByRole('button', { name: '收纳袋 · 1' }))
    fireEvent.click(screen.getByRole('button', { name: '放回经历册' }))
    fireEvent.click(screen.getByRole('button', { name: '查看误录入的作品' }))
    expect(screen.getByLabelText('名称')).toHaveValue('误录入的作品')
    fireEvent.click(screen.getByRole('button', { name: '删除这张卡片' }))
    fireEvent.click(screen.getByRole('button', { name: '删除并移入收纳袋' }))
    fireEvent.click(screen.getByRole('button', { name: '永久删除误录入的作品' }))
    fireEvent.click(screen.getByRole('button', { name: '先保留' }))
    expect(useLibraryStore.getState().data.experiences?.entries.find(item => item.id === id)).toBeDefined()
    fireEvent.click(screen.getByRole('button', { name: '永久删除误录入的作品' }))
    fireEvent.click(within(screen.getByRole('dialog')).getByRole('button', { name: '永久删除' }))
    expect(useLibraryStore.getState().data.experiences?.entries.find(item => item.id === id)).toBeUndefined()
    expect(screen.queryByText('误录入的作品')).not.toBeInTheDocument()
  })
  it('keeps unsaved text in memory when navigating away and clears it on discard', () => {
    const first = render(<ExperiencesView />)
    fireEvent.click(screen.getByRole('button', { name: '收进一部作品' }))
    fireEvent.change(screen.getByLabelText('名称'), { target: { value: '暂未保存的作品' } })
    first.unmount()
    render(<ExperiencesView />)
    fireEvent.click(screen.getByRole('button', { name: '收进一部作品' }))
    expect(screen.getByLabelText('名称')).toHaveValue('暂未保存的作品')
    fireEvent.click(screen.getByRole('button', { name: '先放下' }))
    fireEvent.click(screen.getByRole('button', { name: '放下修改' }))
    fireEvent.click(screen.getByRole('button', { name: '收进一部作品' }))
    expect(screen.getByLabelText('名称')).toHaveValue('')
  })
  it('keeps draft text when cover lookup fails and warns before discarding edits', async () => {
    render(<ExperiencesView />)
    fireEvent.click(screen.getByRole('button', { name: '收进一部作品' }))
    const editor = within(screen.getByLabelText('经历卡片编辑'))
    fireEvent.change(editor.getByLabelText('名称'), { target: { value: '冷门小说' } })
    expect(editor.getByText('换个来源 / 用作品链接').parentElement).not.toHaveAttribute('open')
    fireEvent.click(editor.getByRole('button', { name: '找封面' }))
    expect(await editor.findByText('未配置微信读书密钥')).toBeInTheDocument()
    expect(editor.getByLabelText('名称')).toHaveValue('冷门小说')
    fireEvent.click(editor.getByRole('button', { name: '关闭经历编辑' }))
    expect(screen.getByRole('dialog', { name: '先放下这张卡片？' })).toBeInTheDocument()
    fireEvent.click(screen.getByRole('button', { name: '先保留' }))
    expect(editor.getByLabelText('名称')).toHaveValue('冷门小说')
    fireEvent.click(editor.getByRole('button', { name: '保存这一页' }))
    await waitFor(() => expect(useLibraryStore.getState().data.experiences?.entries).toHaveLength(1))
  })
})
