import { describe,expect,it } from 'vitest'
import { createSeedLibrary } from '../domain/seed'
import { buildCompanionContext } from './companionSlice'
import { companionDesktopSnapshot } from '../modules/companion/companionDesktop'

describe('companion permission context',()=>{
  it('reads only explicitly granted scopes',()=>{const data=createSeedLibrary();expect(buildCompanionContext(data,[]).text).toBe('');data.companion.permissions.chapterIds=[data.session.activeChapterId];expect(buildCompanionContext(data,[]).text).toContain('章节片段')})
  it('requires temporary permission for encrypted works',()=>{const data=createSeedLibrary();const work=data.works[0];work.encrypted=true;work.locked=false;data.companion.permissions.workIds=[work.id];expect(buildCompanionContext(data,[]).text).toBe('');expect(buildCompanionContext(data,[work.id]).text).toContain('章节片段');work.locked=true;expect(buildCompanionContext(data,[work.id]).text).toBe('')})
  it('injects only authorized memories and keeps encrypted-source memories behind the temporary grant',()=>{const data=createSeedLibrary();const work=data.works[0];data.companion.permissions.workIds=[work.id];data.companion.memories=[{id:'memory-1',content:'喜欢安静提醒',source:'manual',sourceLabel:'手动',createdAt:'2026-08-17T00:00:00Z',updatedAt:'2026-08-17T00:00:00Z',confidence:100,authorized:true},{id:'memory-2',content:'加密来源',source:'conversation',sourceLabel:'对话',sourceWorkId:work.id,createdAt:'2026-08-17T00:00:00Z',updatedAt:'2026-08-17T00:00:00Z',confidence:70,authorized:true}];work.encrypted=true;expect(buildCompanionContext(data,[]).text).toContain('喜欢安静提醒');expect(buildCompanionContext(data,[]).text).not.toContain('加密来源');expect(buildCompanionContext(data,[work.id]).text).toContain('加密来源');data.companion.memories[0].authorized=false;expect(buildCompanionContext(data,[work.id]).text).not.toContain('喜欢安静提醒')})
  it('derives a display-only desktop action without document context',()=>{const data=createSeedLibrary();const snapshot=companionDesktopSnapshot(data.companion,'writing',false);expect(snapshot.action).toBe('idle');expect(snapshot).not.toHaveProperty('permissions');expect(snapshot).not.toHaveProperty('memories')})
  it('keeps the selected portrait in the display-only desktop snapshot',()=>{const data=createSeedLibrary();data.companion.desktop.visual={type:'portrait',assetId:'asset-portrait'};data.assets.push({id:'asset-portrait',fileName:'portrait.png',mimeType:'image/png',size:1,width:100,height:200,sha256:'hash',createdAt:new Date().toISOString(),chapterIds:[]});expect(companionDesktopSnapshot(data.companion,'home',false,data.assets).visual).toEqual({type:'portrait',assetId:'asset-portrait'})})
})
