import type { JSONContent } from '@tiptap/react'
import type { AgentNavigationIntent, AiGeneration, AnswerBookFavorite, Asset, BackgroundSettings, CalendarEvent, CompanionAgentAuditEntry, CompanionDesktopMode, CompanionMemory, CompanionMessage, CompanionPersonality, CompanionVideoState, Course, DailyQuestion, DiaryEntry, EntityRef, LibraryData, MoodEntry, Person, Place, PlaybackContextKind, RecordType, SaveStatus, TextAnchor, ThemeId, TimelineEvent, TodoItem, Track, ViewId } from '../domain/models'
import type { HealthStatus, RecoveryDraft } from '../infrastructure/libraryRepository'
import type { ImportChapter } from '../infrastructure/documentTransfer'

export interface LibraryStore {
  data: LibraryData; ready: boolean; saveStatus: SaveStatus; health: HealthStatus | null; recoveryDrafts: Record<string, RecoveryDraft>; playback: { playing: boolean; context: PlaybackContextKind; queue: string[] }; temporaryCompanionWorkIds: string[]
  hydrate: () => Promise<void>; navigate: (view: ViewId) => void; openAgentDestination: (intent: Omit<AgentNavigationIntent, 'id'>) => void; selectWork: (id: string) => void; selectChapter: (id: string) => void; closeChapter: (id: string) => void
  createWork: () => void; renameWork: (id: string, title: string) => void; trashWork: (id: string) => void
  createChapter: () => void; createVolume: () => void; renameVolume: (id: string, title: string) => void; trashVolume: (id: string) => void
  importChapters: (workId: string, chapters: ImportChapter[]) => void
  moveChapter: (id: string, direction: -1 | 1) => void; reorderChapter: (sourceId: string, targetId: string) => void; trashChapter: (id: string) => void; restoreChapter: (id: string) => void; permanentlyDeleteChapter: (id: string) => void; renameChapter: (id: string, title: string) => void
  saveChapter: (id: string, content: JSONContent, plainText: string) => Promise<void>; createManualVersion: (id: string) => Promise<void>; restoreVersion: (chapterId: string, versionId: string) => Promise<void>; toggleVersionPinned: (chapterId: string, versionId: string) => void
  addPerson: () => void; addPlace: () => void; addEvent: () => void; createRecordFromText: (type: RecordType, label: string, chapterId: string, anchor: TextAnchor) => EntityRef
  importAsset: (file: File, context?: { workId?: string; chapterId?: string; purpose?: Asset['purpose'] }) => Promise<Asset>; importCompanionVideo: (file: File, onProgress?: (message: string) => void) => Promise<Asset>; updateAsset: (id: string, changes: Pick<Asset, 'alt' | 'caption'>) => void; trashAsset: (id: string) => void; restoreAsset: (id: string) => void; permanentlyDeleteAsset: (id: string) => Promise<void>; cleanupUnusedCompanionAssets: () => Promise<number>; linkAssetToChapter: (assetId: string, chapterId: string) => void; setChapterImpression: (chapterId: string, assetId: string) => void; recordAiGeneration: (generation: AiGeneration) => void
  updatePerson: (id: string, changes: Pick<Person, 'name' | 'aliases' | 'summary' | 'importantExperiences' | 'tags' | 'customFields'>) => void
  updatePlace: (id: string, changes: Pick<Place, 'name' | 'aliases' | 'region' | 'address' | 'relatedPeriod' | 'description' | 'tags' | 'customFields'>) => void
  updateEvent: (id: string, changes: Pick<TimelineEvent, 'title' | 'displayTime' | 'precision' | 'startDate' | 'endDate' | 'sortTime' | 'description' | 'customFields'>) => void
  trashRecord: (type: RecordType, id: string) => void; restoreRecord: (type: RecordType, id: string) => void; permanentlyDeleteRecord: (type: RecordType, id: string) => void
  setChapterLink: (chapterId: string, target: EntityRef, linked: boolean, anchor?: TextAnchor) => void; setRecordLink: (source: EntityRef, target: EntityRef, linked: boolean) => void; openRecord: (record: EntityRef) => void; pinRecord: (record?: EntityRef) => void
  addPersonRelation: (fromId: string, toId: string, relationType: string, description: string) => void; deletePersonRelation: (id: string) => void; moveEvent: (id: string, direction: -1 | 1) => void
  setTheme: (theme: ThemeId) => void; toggleRightPanel: () => void; setDailyTarget: (target: number) => void; setLayoutProfile: (profile: LibraryData['settings']['layoutProfile']) => void; setBackgroundImage: (image?: string) => void; setBackgroundSettings: (changes: { images?: Partial<BackgroundSettings['images']>; sidebarMode?: BackgroundSettings['sidebarMode'] }) => void; moveNavigation: (view: ViewId, direction: -1 | 1) => void; toggleModule: (id: LibraryData['settings']['modules'][number]['id']) => void; toggleFocusMode: () => void
  setAiSettings: (changes: Partial<LibraryData['settings']['ai']>) => void; setWebSearchSettings: (changes: Partial<LibraryData['settings']['webSearch']>) => void; setBackupSettings: (changes: Partial<LibraryData['settings']['backup']>) => void; setSecuritySettings: (changes: Partial<LibraryData['settings']['security']>) => void; setTrustSettings: (changes: Partial<LibraryData['settings']['trust']>) => void
  saveDiaryEntry: (entry: DiaryEntry) => void; addCourse: (course: Omit<Course, 'id'>) => void; updateCourse: (id: string, changes: Partial<Omit<Course, 'id'>>) => void; deleteCourse: (id: string) => void
  saveMoodEntry: (entry: Pick<MoodEntry, 'date' | 'period' | 'points' | 'note'>) => void; deleteMoodEntry: (id: string) => void
  addCalendarEvent: (event: Omit<CalendarEvent, 'id'>) => void; updateCalendarEvent: (id: string, changes: Partial<Omit<CalendarEvent, 'id'>>) => void; deleteCalendarEvent: (id: string) => void
  openDiary: (date: string) => void; saveDailyQuestion: (question: DailyQuestion) => void; startDailyQuestionDiary: (question: DailyQuestion) => void
  addTodo: (draft: Pick<TodoItem, 'title' | 'repeat' | 'dueDate' | 'repeatDays' | 'quotaPeriod' | 'quotaTarget'>) => void; updateTodo: (id: string, changes: Partial<Omit<TodoItem, 'id' | 'createdAt'>>) => void; toggleTodoForDate: (id: string, date: string) => void; toggleTodoHoliday: (date: string) => void; recordTodoCompletion: (id: string) => void; removeTodoCompletion: (id: string, completionId: string) => void; deleteTodo: (id: string) => void
  addAnswerBookFavorite: (favorite: Pick<AnswerBookFavorite, 'question' | 'answer'>) => void; deleteAnswerBookFavorite: (id: string) => void
  importTrack: (file: File) => Promise<Track>; updateTrack: (id: string, changes: Pick<Track, 'title' | 'artist'>) => void; trashTrack: (id: string) => void; restoreTrack: (id: string) => void; permanentlyDeleteTrack: (id: string) => Promise<void>; setMusicContext: (kind: PlaybackContextKind, scopeId: string | undefined, trackIds: string[]) => void; playTrack: (id: string, context?: PlaybackContextKind) => void; togglePlayback: () => void; nextTrack: () => void; previousTrack: () => void; setMusicSettings: (changes: Partial<LibraryData['settings']['music']>) => void
  setCompanionProfile: (changes: Partial<Pick<LibraryData['companion'], 'name' | 'expression'>>) => void; setCompanionAppearance: (changes: Partial<LibraryData['companion']['appearance']>) => void; setCompanionDesktop: (visible: boolean) => void; setCompanionDesktopMode: (mode: CompanionDesktopMode) => void; setCompanionShortcut: (shortcut: string) => void; setCompanionQuietShortcut: (shortcut: string) => void; setCompanionPortrait: (assetId?: string) => void; setCompanionVideo: (state: CompanionVideoState, assetId?: string) => void; addCompanionVideo: (state: CompanionVideoState, assetId: string) => void; removeCompanionVideo: (state: CompanionVideoState, assetId: string) => void; setCompanionProvider: (changes: Partial<LibraryData['companion']['provider']>) => void; setCompanionVoice: (changes: { stt?: Partial<LibraryData['companion']['voice']['stt']>; tts?: Partial<LibraryData['companion']['voice']['tts']>; autoSpeak?: boolean; wakeEnabled?: boolean; wakeWord?: string; wakeSensitivity?: LibraryData['companion']['voice']['wakeSensitivity']; speakerVerification?: boolean; modelDownloadSource?: LibraryData['companion']['voice']['modelDownloadSource']; replyLength?: LibraryData['companion']['voice']['replyLength']; longReplySpeech?: LibraryData['companion']['voice']['longReplySpeech'] }) => void; setCompanionPermissions: (changes: Partial<LibraryData['companion']['permissions']>) => void; setCompanionComputer: (changes: Partial<LibraryData['companion']['computer']>) => void; grantTemporaryCompanionWork: (id: string, allowed: boolean) => void; addCompanionMessage: (message: CompanionMessage) => void; addCompanionAudit: (entries: CompanionAgentAuditEntry[]) => void; clearCompanionMessages: () => void
  addCompanionMemory: (content: string, source: CompanionMemory['source'], sourceLabel: string, sourceWorkId?: string) => boolean; updateCompanionMemory: (id: string, changes: Partial<Pick<CompanionMemory, 'content' | 'confidence' | 'authorized'>>) => void; deleteCompanionMemory: (id: string) => void; setCompanionGrowthEnabled: (enabled: boolean) => void; setCompanionPersonality: (changes: Partial<CompanionPersonality>, reason: string) => void; rollbackCompanionGrowth: (id: string) => void; resetCompanionPersonality: () => void
  encryptWork: (workId: string, password: string) => Promise<void>; unlockWork: (workId: string, password: string) => Promise<void>; lockWork: (workId: string) => Promise<void>; lockAllWorks: () => Promise<void>; refreshVaultLocks: () => Promise<void>
  updateChapterSession: (id: string, cursor: number, scroll: number) => void; saveRecoveryDraft: (id: string, content: JSONContent, plainText: string) => Promise<void>; restoreRecoveryDraft: (id: string) => void; discardRecoveryDraft: (id: string) => Promise<void>
}
