import { act, renderHook } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { useNativePetDrag } from './useNativePetDrag'
const native = vi.hoisted(() => ({ drag: vi.fn(), invoke: vi.fn() }))
vi.mock('@tauri-apps/api/window', () => ({ getCurrentWindow: () => ({ startDragging: native.drag }) }))
vi.mock('@tauri-apps/api/core', () => ({ invoke: native.invoke }))
describe('native dragging release detection', () => {
  beforeEach(() => { vi.useFakeTimers(); vi.clearAllMocks(); native.drag.mockResolvedValue(undefined); native.invoke.mockResolvedValue(true) })
  afterEach(() => vi.useRealTimers())
  it('does not snap when startDragging resolves; waits until primary button release', async () => {
    const start = vi.fn(), end = vi.fn(), error = vi.fn()
    const { result } = renderHook(() => useNativePetDrag(start, end, error))
    await act(async () => result.current())
    expect(start).toHaveBeenCalledTimes(1); expect(end).not.toHaveBeenCalled()
    await act(async () => vi.advanceTimersByTimeAsync(160))
    expect(end).not.toHaveBeenCalled()
    native.invoke.mockResolvedValue(false)
    await act(async () => vi.advanceTimersByTimeAsync(80))
    expect(end).toHaveBeenCalledTimes(1); expect(error).not.toHaveBeenCalled()
    await act(async () => vi.advanceTimersByTimeAsync(800))
    expect(end).toHaveBeenCalledTimes(1)
  })
  it('uses native pointerup once and cancels late polls/unmounts', async () => {
    const end = vi.fn()
    const { result, unmount } = renderHook(() => useNativePetDrag(undefined, end))
    await act(async () => result.current())
    act(() => window.dispatchEvent(new MouseEvent('pointerup', { button: 0 })))
    expect(end).toHaveBeenCalledTimes(1)
    await act(async () => vi.advanceTimersByTimeAsync(100))
    expect(native.invoke).not.toHaveBeenCalled()
    await act(async () => result.current())
    unmount()
    await act(async () => vi.advanceTimersByTimeAsync(1000))
    expect(end).toHaveBeenCalledTimes(1)
  })
  it('reports a failed native start rather than snapping and tolerates unavailable button queries', async () => {
    native.drag.mockRejectedValueOnce(Error('denied'))
    const end = vi.fn(), error = vi.fn()
    const { result } = renderHook(() => useNativePetDrag(undefined, end, error))
    await act(async () => result.current())
    expect(error).toHaveBeenCalledTimes(1); expect(end).not.toHaveBeenCalled()
    native.invoke.mockRejectedValue(Error('unsupported'))
    await act(async () => result.current())
    await act(async () => vi.advanceTimersByTimeAsync(80))
    act(() => window.dispatchEvent(new MouseEvent('pointerup', { button: 0 })))
    expect(end).toHaveBeenCalledTimes(1)
  })
})
