import { invoke } from '@tauri-apps/api/core'
import type { AiGeneration, Asset, Chapter, EntityLink, LibraryData, Volume, Work } from '../domain/models'
import { assetRepository } from './assetRepository'

export interface VaultPayload { work: Work; chapters: Record<string, Chapter>; volumes: Volume[]; entityLinks: EntityLink[]; assets: Asset[]; aiGenerations: AiGeneration[]; assetBytes: { id: string; mimeType: string; bytes: number[] }[] }
const isTauriRuntime = () => '__TAURI_INTERNALS__' in window

function workParts(data: LibraryData, workId: string) { const chapterIds = new Set(Object.values(data.chapters).filter((chapter) => chapter.workId === workId).map((chapter) => chapter.id)); const assets = data.assets.filter((asset) => asset.workId === workId || asset.chapterIds.some((id) => chapterIds.has(id))); return { chapterIds, assets } }

async function payloadFor(data: LibraryData, workId: string): Promise<VaultPayload> {
  const work = data.works.find((item) => item.id === workId); if (!work) throw new Error('找不到要加密的作品')
  const { chapterIds, assets } = workParts(data, workId)
  const assetBytes = await Promise.all(assets.map(async (asset) => ({ id: asset.id, mimeType: asset.mimeType, bytes: [...await assetRepository.readBytes(asset)] })))
  return { work: { ...work, locked: false }, chapters: Object.fromEntries(Object.entries(data.chapters).filter(([, chapter]) => chapter.workId === workId)), volumes: data.volumes.filter((volume) => volume.workId === workId), entityLinks: data.entityLinks.filter((link) => link.sourceType === 'chapter' && chapterIds.has(link.sourceId) || link.targetType === 'chapter' && chapterIds.has(link.targetId)), assets, aiGenerations: data.aiGenerations.filter((generation) => chapterIds.has(generation.sourceId)), assetBytes }
}

export function sanitizeEncryptedWork(data: LibraryData, workId: string): LibraryData {
  const work = data.works.find((item) => item.id === workId); if (!work?.vaultId) return data
  const { chapterIds, assets } = workParts(data, workId); const assetIds = new Set(assets.map((asset) => asset.id)); const active = data.session.activeWorkId === workId
  const stub: Work = { id: work.id, kind: work.kind, title: '已锁定作品', description: '', chapterIds: [], targetWords: work.targetWords, createdAt: work.createdAt, updatedAt: work.updatedAt, volumeIds: [], encrypted: true, locked: true, vaultId: work.vaultId }
  return { ...data, works: data.works.map((item) => item.id === workId ? stub : item), chapters: Object.fromEntries(Object.entries(data.chapters).filter(([, chapter]) => chapter.workId !== workId)), volumes: data.volumes.filter((volume) => volume.workId !== workId), entityLinks: data.entityLinks.filter((link) => !(link.sourceType === 'chapter' && chapterIds.has(link.sourceId)) && !(link.targetType === 'chapter' && chapterIds.has(link.targetId))), assets: data.assets.filter((asset) => !assetIds.has(asset.id)), aiGenerations: data.aiGenerations.filter((generation) => !chapterIds.has(generation.sourceId)), session: active ? { ...data.session, activeView: 'writing', activeChapterId: '', openChapterIds: [] } : data.session }
}

export const vaultRepository = {
  async create(data: LibraryData, workId: string, password: string, ttl: number) { if (!isTauriRuntime()) throw new Error('作品级加密仅在 Windows 桌面版可用'); const vaultId = `vault-${crypto.randomUUID()}`; const prepared = { ...data, works: data.works.map((work) => work.id === workId ? { ...work, encrypted: true, locked: false, vaultId } : work) }; const payload = await payloadFor(prepared, workId); await invoke('create_vault', { id: vaultId, password, payload, ttlMinutes: ttl }); for (const asset of payload.assets) await assetRepository.deletePlainFile(asset); return sanitizeEncryptedWork(prepared, workId) },
  async unlock(data: LibraryData, workId: string, password: string, ttl: number) { const stub = data.works.find((work) => work.id === workId); if (!stub?.vaultId) throw new Error('作品没有加密容器'); const payload = await invoke<VaultPayload>('unlock_vault', { id: stub.vaultId, password, ttlMinutes: ttl }); payload.assetBytes.forEach((item) => assetRepository.registerUnlocked(item.id, item.mimeType, item.bytes)); return { ...data, works: data.works.map((work) => work.id === workId ? { ...payload.work, encrypted: true, locked: false, vaultId: stub.vaultId } : work), chapters: { ...data.chapters, ...payload.chapters }, volumes: [...data.volumes, ...payload.volumes.filter((volume) => !data.volumes.some((item) => item.id === volume.id))], entityLinks: [...data.entityLinks, ...payload.entityLinks.filter((link) => !data.entityLinks.some((item) => item.id === link.id))], assets: [...data.assets, ...payload.assets.filter((asset) => !data.assets.some((item) => item.id === asset.id))], aiGenerations: [...data.aiGenerations, ...payload.aiGenerations.filter((generation) => !data.aiGenerations.some((item) => item.id === generation.id))], session: { ...data.session, activeWorkId: workId, activeChapterId: payload.work.chapterIds[0] ?? '', openChapterIds: payload.work.chapterIds[0] ? [payload.work.chapterIds[0]] : [], activeView: 'writing' as const } } },
  async sealForPersistence(data: LibraryData) { let persistent = data; for (const work of data.works.filter((item) => item.encrypted && !item.locked && item.vaultId)) { const payload = await payloadFor(data, work.id); await invoke('save_vault', { id: work.vaultId, payload, ttlMinutes: data.settings.security.autoLockMinutes }); for (const asset of payload.assets) await assetRepository.deletePlainFile(asset); persistent = sanitizeEncryptedWork(persistent, work.id) } return persistent },
  async lock(data: LibraryData, workId: string) { const work = data.works.find((item) => item.id === workId); if (!work?.vaultId) return data; await invoke('lock_vault', { id: work.vaultId }); assetRepository.clearUnlocked(workParts(data, workId).assets.map((asset) => asset.id)); return sanitizeEncryptedWork(data, workId) },
  async lockAll(data: LibraryData) { await invoke('lock_all_vaults'); let locked = data; for (const work of data.works.filter((item) => item.encrypted && !item.locked)) { assetRepository.clearUnlocked(workParts(data, work.id).assets.map((asset) => asset.id)); locked = sanitizeEncryptedWork(locked, work.id) } return locked },
  async isUnlocked(vaultId: string) { return invoke<boolean>('vault_unlocked', { id: vaultId }) },
}
