import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { emptyHeartRate, useHeartRateStore } from './heartRate'
import { HEART_CONNECTION_KEY, emptyConnectionPreferences, readConnectionPreferences } from './connectionPreferences'
const ipc = vi.hoisted(() => ({ invoke: vi.fn() }))
vi.mock('@tauri-apps/api/core', () => ({ invoke: ipc.invoke }))
const device = { id: `hr-${'a'.repeat(64)}`, name: 'Forerunner 265' }
const other = { id: `hr-${'b'.repeat(64)}`, name: 'Forerunner 265' }
const idle = { ...emptyHeartRate, phase: 'idle' as const, devices: [device] }
const connected = { ...idle, phase: 'connected' as const, deviceName: device.name, bpm: 72, ageMs: 0 }
const remember = (autoConnect = false) => useHeartRateStore.setState({ preferences: { version: 1, device, autoConnect } })
beforeEach(() => {
  vi.useFakeTimers(); vi.setSystemTime(new Date('2026-10-05T12:00:00'))
  localStorage.clear()
  Object.defineProperty(window, '__TAURI_INTERNALS__', { configurable: true, value: {} })
  useHeartRateStore.setState({ enabled: false, status: emptyHeartRate, revision: 0, preferences: { ...emptyConnectionPreferences }, preferencesSaved: true, initialized: false, pendingDevice: null, reconnectTarget: null, retryAt: null, retryAttempt: 0 })
  ipc.invoke.mockReset().mockResolvedValue(emptyHeartRate)
})
afterEach(() => { vi.useRealTimers(); delete (window as unknown as Record<string, unknown>).__TAURI_INTERNALS__ })
describe('remembered heart rate connection', () => {
  it('remembers only after the native connection succeeds', async () => {
    useHeartRateStore.setState({ enabled: true, status: idle })
    ipc.invoke.mockResolvedValue({ ...idle, phase: 'connecting' })
    await useHeartRateStore.getState().connect(device.id)
    expect(readConnectionPreferences().device).toBeNull()
    ipc.invoke.mockResolvedValue(connected)
    await useHeartRateStore.getState().refresh()
    expect(readConnectionPreferences()).toEqual({ version: 1, device, autoConnect: false })
    expect(useHeartRateStore.getState().pendingDevice).toBeNull()
  })
  it('does not remember a failed connection or overwrite the remembered device', async () => {
    remember(); useHeartRateStore.setState({ enabled: true, status: { ...idle, devices: [other] } })
    ipc.invoke.mockResolvedValue({ ...emptyHeartRate, phase: 'error' })
    await useHeartRateStore.getState().connect(other.id)
    await useHeartRateStore.getState().refresh()
    expect(useHeartRateStore.getState().preferences.device).toEqual(device)
    expect(useHeartRateStore.getState().pendingDevice).toBeNull()
  })
  it('finds the remembered identifier on enable, without another chooser', async () => {
    remember()
    ipc.invoke.mockImplementation(async (command) => command === 'heart_rate_scan' ? { ...emptyHeartRate, phase: 'scanning' } : command === 'heart_rate_status' ? idle : { ...idle, phase: 'connecting' })
    await useHeartRateStore.getState().enable()
    expect(ipc.invoke).toHaveBeenCalledWith('heart_rate_scan', undefined)
    await useHeartRateStore.getState().refresh()
    expect(ipc.invoke).toHaveBeenCalledWith('heart_rate_connect', { deviceId: device.id })
  })
  it('never substitutes a same-name device or an id outside the current scan', async () => {
    remember()
    ipc.invoke.mockResolvedValue({ ...idle, devices: [other] })
    await useHeartRateStore.getState().enable()
    await useHeartRateStore.getState().refresh()
    await useHeartRateStore.getState().connect(device.id)
    expect(ipc.invoke.mock.calls.some(([command]) => command === 'heart_rate_connect')).toBe(false)
    expect(useHeartRateStore.getState().retryAt).toBeNull()
    expect(useHeartRateStore.getState().status.message).toMatch(/未找到/)
  })
  it('starts at most once per app session, and only with explicit auto-connect opt-in', async () => {
    remember()
    await useHeartRateStore.getState().resumeOnStartup()
    expect(ipc.invoke).not.toHaveBeenCalled()
    useHeartRateStore.setState({ initialized: false })
    useHeartRateStore.getState().setAutoConnect(true)
    expect(readConnectionPreferences().autoConnect).toBe(true)
    await useHeartRateStore.getState().resumeOnStartup()
    await useHeartRateStore.getState().resumeOnStartup()
    expect(ipc.invoke.mock.calls.filter(([command]) => command === 'heart_rate_scan')).toHaveLength(1)
  })
  it('keeps retry deadlines fixed and stops scanning after three total attempts', async () => {
    remember(true)
    ipc.invoke.mockResolvedValue({ ...idle, devices: [] })
    await useHeartRateStore.getState().resumeOnStartup()
    await useHeartRateStore.getState().refresh()
    const first = useHeartRateStore.getState().retryAt
    vi.advanceTimersByTime(1000)
    await useHeartRateStore.getState().refresh()
    expect(useHeartRateStore.getState().retryAt).toBe(first)
    vi.advanceTimersByTime(14000)
    await useHeartRateStore.getState().refresh()
    await useHeartRateStore.getState().refresh()
    vi.advanceTimersByTime(45000)
    await useHeartRateStore.getState().refresh()
    await useHeartRateStore.getState().refresh()
    vi.advanceTimersByTime(60000)
    await useHeartRateStore.getState().refresh()
    expect(ipc.invoke.mock.calls.filter(([command]) => command === 'heart_rate_scan')).toHaveLength(3)
    expect(useHeartRateStore.getState().retryAt).toBeNull()
  })
  it('cancels retry on explicit stop, keeps the device, and does not restart this session', async () => {
    remember(true)
    ipc.invoke.mockResolvedValue({ ...idle, devices: [] })
    await useHeartRateStore.getState().resumeOnStartup()
    await useHeartRateStore.getState().refresh()
    expect(useHeartRateStore.getState().retryAt).not.toBeNull()
    await useHeartRateStore.getState().disconnect()
    vi.advanceTimersByTime(120000)
    await useHeartRateStore.getState().refresh()
    await useHeartRateStore.getState().resumeOnStartup()
    expect(ipc.invoke.mock.calls.filter(([command]) => command === 'heart_rate_scan')).toHaveLength(1)
    expect(useHeartRateStore.getState().preferences.device).toEqual(device)
  })
  it('forgets the device and ignores an in-flight reading which would otherwise save it again', async () => {
    remember(true); useHeartRateStore.setState({ enabled: true, status: idle, pendingDevice: device })
    let resolveStatus: ((value: typeof connected) => void) | undefined
    ipc.invoke.mockImplementation((command) => command === 'heart_rate_status' ? new Promise((resolve) => { resolveStatus = resolve }) : Promise.resolve(emptyHeartRate))
    const pending = useHeartRateStore.getState().refresh()
    await useHeartRateStore.getState().forgetDevice()
    resolveStatus?.(connected); await pending
    expect(localStorage.getItem(HEART_CONNECTION_KEY)).toBeNull()
    expect(useHeartRateStore.getState().enabled).toBe(false)
    expect(useHeartRateStore.getState().preferences.device).toBeNull()
  })
})
